### ISSUE TITLE
N/A on avg GPA not centered properly

### ISSUE THREAD

**Issue by timmiehaha** [DickyT/Terp-Course-Helper#1]
I don't know if this was intentional but it would add to graphic consistency

![image](https://user-images.githubusercontent.com/35359774/56170611-24ee7180-5fb0-11e9-8c6b-fa726a25df16.png)

**Comment by DickyT** [comment]
This is unexpected, seems like a styling bug, i am gonna fix it after my exam on Thursday

**Comment by DickyT** [comment]
Fixed https://github.com/DickyT/Terp-Course-Helper/commit/fca6e375c396d7640e4352462924e86cb809beba
